### ISSUE TITLE
MacOS error when closing

### ISSUE THREAD

**Issue by MartinRuz** [ml-research/liground#113]
when having loaded PGNs with multiple games, there is an error when closing Liground

**Comment by Zerthox** [comment]
This was fixed in #87 already. On Mac you can close the renderer window without terminating the main process:
https://github.com/ml-research/liground/blob/71cd31db57bda83204df6085a594f0532d2f4a5e/src/main/index.js#L44-L48

The main process continued to send IPC messages to a non-existant renderer process, which caused the error.

Since we now have moved the engine to a thread in the renderer, we'll no longer run into this problem.
