### ISSUE TITLE
Unwanted changes of board position after a move

### ISSUE THREAD

**Issue by neito5** [ml-research/liground#257]
It happens so often that the bug can be easily reproduced with v0.4.0 on my Windows 10 notebook within a minute. Doesn't matter which engine is used or whether I'm in PvE or Analysis mode. See the gif below where I'm playing against MV-SF 10.

![ezgif-2-7f02a5f091](https://user-images.githubusercontent.com/116843006/204155600-a2ce340e-9b4a-4fd7-8d62-98426acc18e4.gif)

It only happens very rarely in v0.3.0 as far as i can tell.

(An unrelated and minor problem in both versions: The font color of variants played is the same as the background color [#95ABB6] in dark mode, so it's not readable unless I click or hover over the moves of the variation.)

**Comment by QueensGambit** [comment]
Hello @neito5 ,
thank you fort reporting this bug ad the minor bug. It seems like there's a problem with the state.
It looks like two pawns appeared out of nowhere in your case.
Does this happen in other variants too?

**Comment by neito5** [comment]
Thank you for the reply.
I believe it's a bug with Crazyhouse only. No such problem with Atomic, Three-Check or Standard so far. It also only happened once within a few hours with v0.3.0.

Here's another example, maybe it helps in figuring out what's happening. (It looks like it's putting some internal calculation/variation on the board)
![ezgif-3-ea902b3b75](https://user-images.githubusercontent.com/116843006/204284053-550a04c8-575f-483d-bc24-390d00e6b386.gif)

**Comment by ksthicke** [comment]
I'm going to work on this (hopefully within the next couple weeks).

Notes on the issue: (mostly for my future self)

1. It seems to be caused by the fact that the info from the engine is processed after the computer's move has already been made.  In particular, in updateMultiPV in store.js, there is a line that checks if the move is valid or not.  IMO, this check seems to be a hack and should be unnecessary if things are designed properly.  In any case, the issue in Crazyhouse is that the placement moves have the same UCI notation (e.g., P@g3) regardless if it is black or white to move.  Therefore, the move will be valid even if it's the wrong person's turn (i.e., even if the computer already played its move).
2. The engine currently makes its move from enginetime() in PVLines.vue.
3. I propose moving the code that causes the computer to play to somewhere more centralized (store.js).  It should not be run based on the current if-statements in enginetime(), but should rather be run after the engine finishes calculating (and returns "bestmove").  This should fix the issues with things happening out of order (as mentioned in 1).  driver.js already emits a "bestmove" event whenever it sees a "bestmove" output by the engine, so this could be used.  As far as I can tell, nothing currently seems to happen on this event.  Should put the engine.on('bestmove', ...) to catch this event at the bottom of store.js.  Then, put the code that it calls somewhere in store.js.
4. The code currently in enginetime() also limits the time that a move can take if a max depth or number of nodes is set.  This can be done more rigorously by doing this in the input to the engine.  For example, if you want to search to depth 30, but only want the search to take a maximum of 60 seconds, you can send the engine the command "go depth 30 movetime 60000".  Then, it will finish and output a "bestmove" on whichever comes first.  Reference: https://www.wbec-ridderkerk.nl/html/UCIProtocol.html

Possible issue:
1. Need to check if the 50ms queue (in engine.worker.js / sender.js) affects anything, but I think it won't.
